#!/usr/bin/with-contenv sh
# shellcheck shell=sh

/etc/transmission/environment-variables.sh

export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

if [ "$RUN_AS" = root ]; then
    transmission-daemon --foreground
else
    s6-setuidgid "$RUN_AS" transmission-daemon --foreground
fi