#!/usr/bin/with-contenv sh
# shellcheck shell=sh
# Copied from the entrypoint in upstream image (sebdanielsson/docker-wireguard-transmission)

# check for wireguard config, then start wireguard
if [ ! -f /etc/wireguard/"$INTERFACE".conf ]
then
  echo "Could not find /etc/wireguard/$INTERFACE.conf"
  exit 1
fi

if [ -f /etc/wireguard/"$INTERFACE".conf ]
then
    chmod 600 /etc/wireguard/"$INTERFACE".conf
    if ! wg-quick up "$INTERFACE";
    then
      echo "
      wg-quick was unable to create the interface. 
      Please see the logs above
      "
      exit 1
    fi
fi
