#!/usr/bin/with-contenv sh
# shellcheck shell=sh
# Copied from the entrypoint in upstream image (sebdanielsson/docker-wireguard-transmission)

# check for wireguard config, then start wireguard
if [ ! -f /etc/wireguard/"$INTERFACE".conf ]
then
  echo "Could not find /etc/wireguard/$INTERFACE.conf"
  exit 1
fi

if [ -f /etc/wireguard/"$INTERFACE".conf ]
then
    chmod 600 /etc/wireguard/"$INTERFACE".conf
    if ! wg-quick up "$INTERFACE";
    then
      echo "
      wg-quick was unable to create the interface. 
      Please see the logs above
      "
      exit 1
    fi
fi

# make transmission only use the wireguard interface
if [ -n "$KILLSWITCH" ]; then
	WIREGUARDIPV4=$(ip addr show "$KILLSWITCH" | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
	WIREGUARDIPV6=$(ip addr show "$KILLSWITCH" | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d')
  export TRANSMISSION_BIND_ADDRESS_IPV4=$WIREGUARDIPV4
  export TRANSMISSION_BIND_ADDRESS_IPV6=$WIREGUARDIPV6
fi
