#!/usr/bin/with-contenv sh

dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh

dockerize -template /etc/transmission/settings.tmpl:/data/transmission-home/settings.json

chmod 700 /etc/transmission/environment-variables.sh