#!/usr/bin/with-contenv sh
# shellcheck shell=sh
# Contents based on small bit from https://github.com/haugene/docker-transmission-openvpn/blob/e3d27e8172fb50e1532f01a24420a34899285ae7/transmission/start.sh

if [ -e "$TRANSMISSION_HOME/settings.json" ] && [ -n "$OVERWRITE_CONFIGURATION" ]; then
  echo "Transmission configuration file not generated as a file exists at $TRANSMISSION_HOME/settings.json"
else
  if [ ! -d "$TRANSMISSION_HOME" ]; then 
    mkdir -p "${TRANSMISSION_HOME}"
  fi
  dockerize -template /etc/transmission/settings.tmpl:/data/transmission-home/settings.json
  echo "Transmission configuration file generated at $TRANSMISSION_HOME/settings.json"
fi

if [ "$TRANSMISSION_WATCH_DIR_ENABLED" = "true" ] && [ ! -d "$TRANSMISSION_WATCH_DIR" ]; then
  mkdir "$TRANSMISSION_WATCH_DIR"
fi

dockerize -template /etc/transmission/environment-variables.tmpl:/etc/transmission/environment-variables.sh
chmod 700 /etc/transmission/environment-variables.sh
