#!/usr/bin/with-contenv sh
# shellcheck shell=sh


if [ -e "/etc/shadowsocks.json" ] && [ -z "$OVERWRITE_SHADOWSOCKS_CONFIGURATION" ]; then
  echo "Shadowsocks configuration file not generated as a file exists at /etc/shadowsocks.json"
else
  dockerize -template /etc/shadowsocks.tmpl:/etc/shadowsocks.json
  echo "Shadowsocks configuration file generated at /etc/shadowsocks.json"
fi
